language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:nijel/ppa -y
  - sudo apt-get update
  - sudo apt-get install libgammu-dev python-wxgtk2.8 python-bluez
install:
  - pip install codecov python-gammu pytest
script:
  - coverage run --source . --append ./setup.py install
  - coverage run --source . --append py.test
after_script:
  - if [ -f ".coverage" ] ; then codecov ; fi
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
virtualenv:
  system_site_packages: true
