language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:nijel/ppa -y
  - sudo apt-get update
  - sudo apt-get install libgammu-dev python-wxgtk2.8 python-bluez
install:
  - pip install codecov python-gammu pytest pytest-cov
script:
  - py.test --cov=.
  - coverage run --source . --append ./setup.py install
after_script:
  - codecov
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
virtualenv:
  system_site_packages: true
