language: python
python:
  - "2.7"
sudo: false
before_install:
  - sudo add-apt-repository ppa:nijel/ppa -y
  - sudo apt-get update
install:
  - pip install codecov python-gammu pytest pytest-cov PyBluez
script:
  - py.test --cov=.
  - coverage run --source . --append ./setup.py install
after_script:
  - codecov
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
virtualenv:
  system_site_packages: true
addons:
  apt:
    sources:
    - gammu
    packages:
    - libgammu-dev
    - python-wxgtk2.8
    - libbluetooth-dev
